# pub keys
keys:
  - &users:
    - &muddy age10ar32v7r7pdx27kyt0qmqhm2ccs4emy8knzztnyjm0xhy82gkqcqwv2299
  - &hosts:
    - &laptop age1fw28hhf8c8z9vq27kra9l2gthy56w7gt8wr0kcdpc0mscg0xegps324hul
    - &laptop-vm age1v3slyg9sas6jxrucwntcu3mhplj94ay2gcntclz4ld43gkwpg9cq9g0d2t
    
    - &desktop age1z3802f2k2cagv7734g50f2n582gwzr7hs37ccg2n2y54n0sheufqkgmwrt

creation_rules:
- path_regex: secrets.yaml$
  key_groups:
    - age:
      - *muddy
      - *laptop
      - *laptop-vm
      - *desktop
