# pub keys
keys:
  - &users:
    - &muddy age10ar32v7r7pdx27kyt0qmqhm2ccs4emy8knzztnyjm0xhy82gkqcqwv2299
  - &hosts:
    - &laptop age1gwndcsc65m0r2cycr0zzzdpz5ns5g96gkw7z2z6nn932fdjn59kqa2vjz4
    # replace with output of: cat /mnt/persist/etc/ssh/id_ed25519.pub | ssh-to-age

    - &laptop-vm age13vaqyw4dmfxz8ql7hwgg60m0rdr8vgcwvlyx43tphuwm8m36ufqqzhtcxw

creation_rules:
- path_regex: secrets.yaml$
  key_groups:
    - age:
      - *muddy
      - *laptop
      - *laptop-vm
